services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_SERVER: 1civilit-Server
    volumes:
      - "./servers.json:/pgadmin4/servers.json"
    ports:
      - "8080:80"
    networks:
      - postgres_network

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres  
    volumes:
      - ./init-script/report_service_db.sql:/docker-entrypoint-initdb.d/report_service_db.sql
      - ./init-script/reportReview_service_db.sql:/docker-entrypoint-initdb.d/reportReview_service_db.sql
      - ./init-script/user_service_db.sql:/docker-entrypoint-initdb.d/user_service_db.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
